export const CAR_LOGOS: { [brandName: string]: string } = {
  TOYOTA: '../../assets/LOGOS/toyota.jpg',
  RENAULT: '../../assets/LOGOS/renault.jpg',
  FORD: '../../assets/LOGOS/ford.jpg',
  BMW: '../../assets/LOGOS/bmw.jpg',
  MERCEDES: '../../assets/LOGOS/mercedes.jpg',
  HONDA: '../../assets/LOGOS/honda.jpg',
  TESLA: '../../assets/LOGOS/tesla.jpg',
  AUDI: '../../assets/LOGOS/audi.jpg',
  CHEVROLET: '../../assets/LOGOS/chevrolet.jpg',
  VOLKSWAGEN: '../../assets/LOGOS/volkswagen.jpg',
  NISSAN: '../../assets/LOGOS/nissan.jpg',
  HYUNDAI: '../../assets/LOGOS/hyundai.jpg',
  KIA: '../../assets/LOGOS/kia.jpg',
  SUBARU: '../../assets/LOGOS/subaru.jpg',
  LEXUS: '../../assets/LOGOS/lexus.jpg',
  MAZDA: '../../assets/LOGOS/mazda.jpg',
  INFINITI: '../../assets/LOGOS/infiniti.jpg',
  ACURA: '../../assets/LOGOS/acura.jpg',
  'LAND ROVER': '../../assets/LOGOS/landrover.jpg',
  JAGUAR: '../../assets/LOGOS/jaguar.jpg',
  VOLVO: '../../assets/LOGOS/volvo.jpg',
  PORSCHE: '../../assets/LOGOS/porsche.jpg',
  FIAT: '../../assets/LOGOS/fiat.jpg',
  MITSUBISHI: '../../assets/LOGOS/mitsubishi.jpg',
  JEEP: '../../assets/LOGOS/jeep.jpg',
  'MINI COOPER': '../../assets/LOGOS/minicooper.jpg',
  PEUGEOT: '../../assets/LOGOS/peugeot.jpg',
  CITROEN: '../../assets/LOGOS/citroen.jpg',
  SKODE: '../../assets/LOGOS/skoda.jpg',
  SEAT: '../../assets/LOGOS/seat.jpg',
  OPEL: '../../assets/LOGOS/opel.jpg',
  SUZUKI: '../../assets/LOGOS/suzuki.jpg',
  ISUZU: '../../assets/LOGOS/isuzu.jpg',
  MG: '../../assets/LOGOS/mg.jpg',
  FERRARI: '../../assets/LOGOS/ferrari.jpg',
  LAMBORGHINI: '../../assets/LOGOS/lamborghini.jpg',
  MASERATI: '../../assets/LOGOS/maserati.jpg',
  AstonMartin: '../../assets/LOGOS/astonmartin.jpg',
  Bugatti: '../../assets/LOGOS/bugatti.jpg',
  'ROLLS ROYCE': '../../assets/LOGOS/rollsroyce.jpg',
  BENTLEY: '../../assets/LOGOS/bentley.jpg',
  LANCIA: '../../assets/LOGOS/lancia.jpg',
  IVECO: '../../assets/LOGOS/iveco.jpg',
  LADA: '../../assets/LOGOS/lada.jpg',
};
