spring.application.name=springJwt
server.port=8084

# Turn off default autoconfiguration
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.allow-bean-definition-overriding=true

# Primary Database
spring.datasource.primary.jdbcUrl=jdbc:postgresql://localhost:5432/portaildb
spring.datasource.primary.username=#your-db-username
spring.datasource.primary.password=#your-db-password
spring.datasource.primary.driverClassName=org.postgresql.Driver

# Secondary Database
spring.datasource.secondary.jdbcUrl=jdbc:postgresql://localhost:5432/BaseEcu
spring.datasource.secondary.username=#your-db-username
spring.datasource.secondary.password=#your-db-password
spring.datasource.secondary.driverClassName=org.postgresql.Driver

spring.profiles.active=dev

# JPA Platform
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
# Generate your own secret, e.g.: openssl rand -hex 32
application.security.jwt.secret-key=#your-jwt-secret-key
application.security.jwt.access-token-expiration=86400000
application.security.jwt.refresh-token-expiration=604800000

# Email settings (Optional, if you're using email)
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=#your-email-address
spring.mail.password=#your-email-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App Configuration
app.verification.base-url= http://localhost:4204/verify?token=

spring.datasource.secondary.jpa.hibernate.ddl-auto=update
spring.datasource.secondary.jpa.show-sql=true

#logging.level.root=DEBUG
